# .github/workflows/change-tracker.yml
name: Firecrawl Change Tracker
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  track:
    runs-on: ubuntu-latest
    concurrency:
      group: tracker
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install --quiet -r requirements.txt
      - name: Run tracker
        env:
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
        run: python -m ai_lab_tracker.cli
