# .github/workflows/change-tracker.yml
name: Firecrawl Change Tracker
on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:
jobs:
  track:
    runs-on: ubuntu-latest
    concurrency:
      group: tracker
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: ~/.cache/uv
          key: ${{ runner.os }}-uv-${{ hashFiles('requirements.txt') }}
      - name: Install deps
        run: |
          # Download UV CLI binary
          curl -Ls https://github.com/astral-sh/uv/releases/latest/download/uv-$(uname -s | tr A-Z a-z)-x86_64 -o uv
          chmod +x uv && sudo mv uv /usr/local/bin
          # Install Python dependencies via UV
          uv pip install --quiet -r requirements.txt
      - name: Run tracker
        env:
          FIRECRAWL_API_KEY: ${{ secrets.FIRECRAWL_API_KEY }}
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
        run: python -m ai_lab_tracker.cli
